=== awsugmys/awsugmys-website/.astro/collections/collaborations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "default": "event",
      "type": "string",
      "enum": [
        "event",
        "organization",
        "community"
      ]
    },
    "date": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "year": {
      "type": "integer",
      "minimum": -9007199254740991,
      "maximum": 9007199254740991
    },
    "location": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "logo": {
      "type": "string"
    },
    "blurb": {
      "type": "string"
    },
    "order": {
      "default": 99,
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ]
}

=== awsugmys/awsugmys-website/src/content/collaborations/aws-community-day-bengaluru-2026.json
{
  "name": "AWS Community Day Bengaluru 2026",
  "type": "event",
  "date": "2026-07-11",
  "location": "Bengaluru",
  "logo": "../../assets/collaborations/aws-community-day-bengaluru-2026.png",
  "blurb": "Joined fellow AWS communities to volunteer and take part in the regional Community Day.",
  "order": 1
}
