=== awsugmys/awsugmys-website/.astro/collections/studentGroups.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "institution": {
      "type": "string"
    },
    "shortName": {
      "type": "string"
    },
    "area": {
      "type": "string",
      "enum": [
        "Mysuru",
        "Mandya"
      ]
    },
    "location": {
      "type": "string"
    },
    "leader": {
      "type": "string"
    },
    "meetupUrl": {
      "type": "string",
      "format": "uri"
    },
    "order": {
      "default": 99,
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "institution",
    "shortName",
    "area",
    "location",
    "meetupUrl"
  ]
}

=== awsugmys/awsugmys-website/src/content/student-groups/mysore-university-school-of-engineering.json
{
  "name": "AWS SBG at Mysore University School of Engineering",
  "institution": "Mysore University School of Engineering",
  "shortName": "MUSE",
  "area": "Mysuru",
  "location": "Manasagangotri, Mysuru",
  "meetupUrl": "https://www.meetup.com/aws-sbg-at-mysore-university-school-of-engineering/",
  "order": 2
}

=== awsugmys/awsugmys-website/src/content/student-groups/vidyavardhaka-college-of-engineering.json
{
  "name": "AWS SBG at Vidyavardhaka College of Engineering",
  "institution": "Vidyavardhaka College of Engineering",
  "shortName": "VVCE",
  "area": "Mysuru",
  "location": "Gokulam, Mysuru",
  "leader": "Yashwanth R",
  "meetupUrl": "https://www.meetup.com/aws-sbg-at-vidyavardhaka-college-of-engineering/",
  "order": 1
}

=== awsugmys/awsugmys-website/src/content/student-groups/g-madegowda-institute-of-technology.json
{
  "name": "AWS SBG at G Madegowda Institute of Technology",
  "institution": "G Madegowda Institute of Technology",
  "shortName": "GMIT",
  "area": "Mandya",
  "location": "Mellahalli, Mandya",
  "leader": "Poorvika M",
  "meetupUrl": "https://www.meetup.com/aws-sbg-at-g-madegowda-institute-of-tech/",
  "order": 4
}

=== awsugmys/awsugmys-website/src/content/student-groups/maharaja-institute-of-technology-thandavapura.json
{
  "name": "AWS SBG at Maharaja Inst of Technology - Thandavapura Campus",
  "institution": "Maharaja Institute of Technology, Thandavapura",
  "shortName": "MIT Thandavapura",
  "area": "Mysuru",
  "location": "Thandavapura, Mysuru",
  "leader": "Rakshitha",
  "meetupUrl": "https://www.meetup.com/aws-sbg-at-maharaja-inst-of-technology-thandavapura-campus/",
  "order": 3
}
